language: node_js
node_js:
  - "6.2"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 6.2.2
branches:
  only:
  - master
services:
  - mongodb
before_script:
  - npm install -g bower grunt-cli
  - bower install
deploy:
  provider: heroku
after_success:
  - bash ./travis/after_success.sh
