language: node_js
node_js:
  - "6.2"
branches:
  only:
  - master
services:
  - mongodb
deploy:
  provider: heroku
after_success:
  - bash ./travis/after_success.sh
  # api_key:
    # secure: "YOUR ENCRYPTED API KEY"
